### ISSUE TITLE
Keep getting this error 

### ISSUE THREAD

**Issue by everyonehello12** [ThereforeGames/txt2mask#11]
<img width="197" alt="Screenshot 2022-09-23 100635" src="https://user-images.githubusercontent.com/112685283/191892899-9bb13e8d-0a87-43eb-885e-c48e60472c63.png">

**Comment by moorehousew** [comment]
You can't download the model weights that the script requires. This is because [timojl/clipseg](https://github.com/timojl/clipseg) is over its LFS quota. Do the following to 'trick' GH into letting you download the model weights.

1. Fork timoji/clipseg
2. Go to repo settings
3. Find "Include Git LFS objects in archives" under the Archives section and check it
4. Go to the Danger Zone section, select "Archive this repository"
5. Confirm and authorize
6. Return to the archived repository
7. Download as .zip

The model weights will be in /weights, move those files to /repositories/clipseg/weights in your SD directory. Dunno why they even used LFS considering the weights are <5mb combined, but there you go.

**Comment by ThereforeGames** [comment]
Thanks for the detailed workaround, @moorehousew!

I just updated the script to point to a download mirror that was mentioned in the clipseg repo. Works on my end, but let me know if the issue persists. Thanks!
