### ISSUE TITLE
Can't replace object masked

### ISSUE THREAD

**Issue by Jonseed** [ThereforeGames/txt2mask#12]
I'm testing it, and I can't seem to get SD to replace the object masked. Perhaps that is just one of the current limitations of img2img. For example, trying to replace the astronaut riding a horse with riding an elephant, and I get strange output like this:

![elephant](https://user-images.githubusercontent.com/40897189/192027915-9f0bb052-8574-4cc1-a4a8-6340da358c9b.jpg)

The mask prompt is "a horse" and the prompt is "an elephant." I can see the script is masking the horse well, but then the elephant is drawn all strange in the masked area. How do you get the astronaut riding an elephant? Again, this might not be a problem with txt2mask specifically, but with the img2img method. Should the top prompt contain a more general description of the entire scene, or only what is going in the masked area?

**Comment by ThereforeGames** [comment]
Hi @Jonseed,

This problem is indeed outside the scope of the txt2mask script - I recommend joining the Stable Diffusion Discord server and posting your question in the #prompt-engineering channel: https://discord.gg/stablediffusion

There are a ton of talented folks there who would be happy to help you out.

That said, here's my advice for getting the most out of img2img:

- When in doubt, use Euler A sampling method. It usually (but not always) produces the best results.
- Around 25 inference steps.
- Turn off "inpainting at full resolution."
- "Original" is often the best masked content mode. I would only use "fill" instead when the content you're trying to add to a picture has *nothing* to do with the original pixels. A horse and an elephant are "close enough" that Original is probably what you want.
- Play around with CFG scale between 7 to 10.
- Denoise strength with Original mode needs to be fairly high sometimes. Start at 0.6 and work your way up to 0.9 if necessary.
- Try a prompt that merely describes the masked area, in your case "an elephant." Sometimes you need to give it a little more context, but I would start simple and work your way up.

Good luck!

**EDIT:** A final thought - it looks like your mask didn't quite select the entire horse, which can negatively impact your result. There are a few ways you can select those hooves: 1) try a multimask like "horse|hooves" or 2) decrease the precision or 3) increase the padding or 4) set "Brush mask mode" to "Add" and manually select the hooves with your brush.

**Comment by Jonseed** [comment]
@ThereforeGames great tips!! Thank you so much! I'll give that a try.

**Comment by ThereforeGames** [comment]
Good luck!

I was kinda curious to see the elephant, so I followed my own advice and I think it turned out pretty well:

![image](https://user-images.githubusercontent.com/95403634/192053936-d12160d1-479b-4d3e-9d61-07a1924a2f16.png)

I did end up selecting the astronaut manually to use as a negative mask. You probably don't have to if you can come up with a good prompt. Here are my full settings:

![image](https://user-images.githubusercontent.com/95403634/192054407-796879cb-c2e6-44ef-99b8-8b7639a6c907.png)

**Comment by Jonseed** [comment]
Yeah, those settings helped it a lot. I think the setting that may have helped the most was changing the masked content from "fill" to "original." When there was nothing there but a big gradient of color, SD didn't know how to put the elephant in the space. But with the horse there, it knows to put the elephant in a similar orientation. I had to take it back into inpaint to add the trunk (since that wasn't part of the original masked horse area), but this is working amazingly well now. Thank you!

![elephant2](https://user-images.githubusercontent.com/40897189/192056017-528c9521-9f54-47ff-beae-00d4016abb91.jpg)

**Comment by ThereforeGames** [comment]
That looks great! Better than mine! 😅
